### ISSUE TITLE
rosinstall_generator complaining about unreleased pkgs that should really be released

### ISSUE THREAD

**Issue by gavanderhoorn** [rosin-project/rosinstall_generator_time_machine#5]
Ref: https://github.com/robust-rosin/robust/issues/55.

**Comment by git-afsantos** [comment]
I am running into this problem for `kobuki:5ee65b0` and now for `kobuki:f95c384` too.

I do not have all the output anymore, but repeating the command yielded the following for `f95c384`.

```
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Retrieving issue 'created_at' property for: https://github.com/yujinrobot/kobuki/issues/331
Found: 2014-07-24T23:23:35Z
Determined rosdistro commit: f20d84fba35d48d12541d12430f7e355bf30b16c
Reusing existing branch
Switched to branch 'bughunt_f95c384'
Skipping rosdistro cache, already exists
Updating temporary rosdistro index ..
Using temporary index to generate rosinstall file (dependencies only) ..
Using ROS_DISTRO: indigo
The following not released packages/stacks will be ignored: kobuki_node
No packages/stacks left after ignoring not released
```

Running `git log` on `bughunt_5ee65b0` gives commit `8c48183908fd79cf44dbce3a404fb170d453adb8` at the top.

On `bughunt_f95c384` it is `f20d84fba35d48d12541d12430f7e355bf30b16c` that comes out at the top.

**Comment by gavanderhoorn** [comment]
Ok. After looking at the bug description, `rosdistro`, the issue and the repository, I think I know what is going on. At least for `5ee65b0`.

The issue in which the bug is reported is `https://github.com/yujinrobot/kobuki/issues/331`. That has a `created_at` of `2014-07-24T23:23:35Z` (as the time machine also reports).

The commit that contains the fix (among many other changes) is https://github.com/yujinrobot/kobuki_desktop/commit/5ee65b061a4a919b2a32e80087f4cb3e51e924ed. That was committed on (approx) `2014-08-08T11:25+2`.

*However*, the `kobuki_desktop` repository was only released into Indigo in https://github.com/ros/rosdistro/commit/93ff6eff16215035afaa05dcc0c9f30ae9140d9c, which was done on `2018-08-11T07:58+2`. That is **3 days later**.

Technically, the output that the time machine (and `rosinstall_generator`) give you is correct: `kobuki_dashboard` was not released at the point in time that you ask it to look for it.

**Comment by gavanderhoorn** [comment]
I realise this is far from easy (or convenient), but I don't believe I can think of a way to work around / resolve this automatically: there is no way for the time machine script to figure this out, it's really up to the human to analyse the flow of events and provide the script with either a URL (in case that should work based on the analysis) *or* a datetime (in cases such as `5ee65b0`).

I'm open to suggestions on how to approach the issue we have here.

**Comment by git-afsantos** [comment]
Hmm, subtle, obscure, convoluted errors, everyone's favourite kind. Shows us not to mess with time, I guess. :smile: 

I agree that this does not seem to be possible (or worth it) to solve automatically.

Running the script with the date of the fix or passing `indigo` as the ROS distro would hopefully work, but then we would be getting newer dependency versions, which might break something else...

**Comment by gavanderhoorn** [comment]
Reproduction-wise I think we can still make this work: officially, `kobuki_desktop` was not released at the time the issue was reported, but I doubt many (if any) of the dependencies of `kobuki_dashboard` changed significantly between when the fix was committed, and when `kobuki_desktop` was actually released into Indigo.

As we only use `rosinstall_generator` to gather a set of dependencies, using the state of `rosdistro` at the time of the release of `kobuki_desktop` (so 3 days later than the `created_at` of the fixing commit) and then use the source repository `kobuki_desktop` as the PUT (with the correct buggy and fixing commits), things should still work out.

There are options to `rosinstall_generator` that make it use the `source` repositories for everything (so instead of the release repositories), but I'm not sure it would be worth the additional work.

Summarising: I would probably recommend to pass a datetime to the time machine instead of the issue URL. In this specific case something a little later than `2014-08-11T05:49:55Z` (which is the `created_at` of the PR against `rosdistro` that introduced https://github.com/ros/rosdistro/commit/93ff6eff16215035afaa05dcc0c9f30ae9140d9c).

**Comment by gavanderhoorn** [comment]
Note that you can easily retrieve the `created_at` property for both issues and PRs with:

```
$ get_issue_creation_date.py https://github.com/ros/rosdistro/pull/5246
```

In this case that is the PR that introduced https://github.com/ros/rosdistro/commit/93ff6eff16215035afaa05dcc0c9f30ae9140d9c.

**Comment by gavanderhoorn** [comment]
@wasowski: this is why creating those `.rosinstall` files is not always as straightforward as just plonking in the right values for the script's args :)

**Comment by gavanderhoorn** [comment]
@git-afsantos: your comment came in as I was finishing https://github.com/rosin-project/rosinstall_generator_time_machine/issues/5#issuecomment-397822664.

As I wrote there, using the `created_at` (+ a little more) of the PR that released `kobuki_desktop` should be ok.

> Hmm, subtle, obscure, convoluted errors, everyone's favourite kind. Shows us not to mess with time, I guess. :smile: 

yes .. 'the universe' doesn't like it :zap: :timer_clock: :hourglass_flowing_sand: .

**Comment by gavanderhoorn** [comment]
Thought: it would probably be good to record the kind of 'sleuthing' that was needed to produce a `.rosinstall` file for a particular bug (in this case `5ee65b0`).

It would seem to be part of the reproduction process, and this way future readers/users can read back and reproduce even the reproduction process if needed.

**Comment by git-afsantos** [comment]
> Thought: it would probably be good to record the kind of 'sleuthing' that was needed to produce a `.rosinstall` file for a particular bug

Do you have something in mind? A list of steps added to the `.bug` file, perhaps?

**Comment by gavanderhoorn** [comment]
@git-afsantos wrote:
> Do you have something in mind? A list of steps added to the `.bug` file, perhaps?

yes, that would probably be a good place to store this.

**Comment by gavanderhoorn** [comment]
I've added a short FAQ to the readme: 444bfe4f9d854704f42bcea3dbc2da714c5c3014.

**Comment by git-afsantos** [comment]
> I would probably recommend to pass a datetime to the time machine instead of the issue URL. In this specific case something a little later than 2014-08-11T05:49:55Z

I just tried this twice. Once with a datetime just one minute after, and after with a datetime a full day after. Both yield the same empty `.rosinstall`.

---

After deleting the cache **and** the `bughunt_5ee65b0` branch from `rosdistro`, it worked. I decided to keep the comment above, to serve as a reminder, in case someone else runs into a similar issue.

**Comment by gavanderhoorn** [comment]
Yeah, that is a shortcoming of the current implementation (I told you it was rather sensitive to the state of your `rosdistro` clone): the name of the branch is based only on the id of the bug. So as long as you're rerunning the command for the same bug id, it'll keep reusing that branch.

I should probably add the rosdistro commit to the branch name as well, that should avoid this.

Not sure whether deleting the cache was really necessary though: the directory name already includes both the datetime you want to go back to, as well as the `rosdistro` commit ([here](https://github.com/rosin-project/rosinstall_generator_time_machine/blob/129565febb0f3a74a28025dfc7d1e7e5b232d1cc/rosinstall_generator_time_machine.sh#L78)). In theory, that should be enough to disambiguate things sufficiently.

**Comment by gavanderhoorn** [comment]
In relation to the reused branch: see e2b2e4adae, where I've reworked how the object name is calculated, and also changed things around to use tags instead of branches.

I used branches earlier as I was thinking of actually committing the changes to the `rosdistro` files, but seeing as there is a little to gain by doing that, tags will do just fine.

**Comment by git-afsantos** [comment]
I deleted the cache just to be safe, but indeed it should not be a problem.

> In relation to the reused branch: see e2b2e4a, where I've reworked how the object name is calculated, and also changed things around to use tags instead of branches.

Nice. This should make things easier (at least less maintenance demanding) for future similar cases.

**Comment by gavanderhoorn** [comment]
I've captured the desire to take a look at using "source repositories" for bugs that seem to require those -- as there are no releases -- in #11.

At least right now, I believe that would be the general approach to dealing with the issue reported here.

As strictly speaking what @git-afsantos reported is not actually an issue with the time machine, I'm going to close this.
